#!/usr/bin/env python

def frequentWords(text, k):
    frequentPatterns = {}
    maxCount = 0 
    for i in range(0, len(text) - k + 1):
        k_mer = text[i:i + k]

        if k_mer in frequentPatterns:
            frequentPatterns[k_mer] += 1
        else:
            frequentPatterns[k_mer] = 1

        if frequentPatterns[k_mer] > maxCount:
            maxCount = frequentPatterns[k_mer]

    frequentPatternsList = []
    for k_mer, count in frequentPatterns.items():
        if count == maxCount:
            frequentPatternsList.append(k_mer)

   
    return frequentPatternsList

frequent = frequentWords("TAGGGCATTAGGGCATTCGCGCGCCATCGCGCGCCACCTTATCTTCGCGCGCCAGTGATACGATTCGCGCGCCATCGCGCGCCAGTGATACGATTCGCGCGCCACCTTATCTCCTTATCTCCTTATCTCCTTATCTCGACTACCCCTTATCTGTGATACGATTAGGGCATGTGATACGATCCTTATCTTAGGGCATTCGCGCGCCAGTGATACGATCGACTACCGTGATACGATCGACTACCCGACTACCTCGCGCGCCATCGCGCGCCACCTTATCTCGACTACCCGACTACCTCGCGCGCCACGACTACCTCGCGCGCCACGACTACCGTGATACGATTAGGGCATTAGGGCATCCTTATCTGTGATACGATTAGGGCATTAGGGCATTAGGGCATCCTTATCTCCTTATCTGTGATACGATCCTTATCTCCTTATCTTCGCGCGCCATAGGGCATCGACTACCCCTTATCTCCTTATCTGTGATACGATCCTTATCTCGACTACCCCTTATCTCCTTATCTCCTTATCTCGACTACCGTGATACGATTCGCGCGCCATCGCGCGCCATAGGGCATTCGCGCGCCATAGGGCATCGACTACCCCTTATCTTAGGGCATTCGCGCGCCAGTGATACGATTCGCGCGCCACCTTATCTCGACTACCCGACTACCTCGCGCGCCACGACTACCTAGGGCATCGACTACCCGACTACCCCTTATCTCGACTACCGTGATACGATTCGCGCGCCACCTTATCTCGACTACCCGACTACCTCGCGCGCCACGACTACCCCTTATCTCGACTACCCCTTATCTCGACTACCCGACTACCTCGCGCGCCAGTGATACGATGTGATACGATCGACTACCGTGATACGATTAGGGCATTCGCGCGCCATCGCGCGCCAGTGATACGATTCGCGCGCCATAGGGCAT",14)
result = " ".join(frequent)
print(result)