#!/usr/bin/env python
theString = "TGGGTGGCGGGCAAAAGGTTTGCTACTCGTGGGTACTATGGGGATGATCACGTGATTCAAAGCGATCGACCGAGCCATGGACCTGATGCTAGTCGCAACAGGACAGGAACTCCTCTTCCAAAATATGTTAAAGTAAGAAAACTATTAATGGCCAACCGCCCCCAGAGTGATTCCTGAATAGGATCTGACATCCTTATGATAAGCAGAAACATTGCGCCCGGTCCGAAGATACCTAGATTAACCCCCACGTTAGATCTATCCAGTGACGGGCGCGCAATTAGTGGCCCATAGAAAAAAGTTTCGGACCTATCCCGCAGGCACGCAGGTTGACCTTCAGCCTAACTGCGATAGAGGCCAAGGTTGATACTGAGCTAACGAAAACCCATGAAGAACGACTGTGTCGAAAGTTGGAAACGTGTTTATCTAATTTCCTGTCTCTTAGGGGAGCATTCCATCAAATCGGGTCCCGGATAAGGTGGGGGGTAAGTTAACCCCGTGGGCGATAGCTTATAGATGAGCTTTCTGCTAGGATATCTGGGTCTAAGATTTGACCCAGTACAATTCAAACCTTTTGATTCACGCTAGACAGCTGAAGTGAAGTGACCTCATAGGGGTTGTATAACGATTAGATGTGTGCTAAGTGCACACCTACAGCTCATACCAGCAGAGGTACTGCTTGAAGGTCGCCGGATGCAGTCTATAAAGAGTGGCAACCGGCTTTCTGCTCCGGCATTCGGTGGCGTTCCTCACCACTGTTACCCGCAACAGGAACCTTACTGTGTCGGATACTGCGGGACCATTCACACTGTACCATGTTCTCTCGAGTTCGATAAAGGTAACTCTAAACGGTACACGTTTAGGCGTAGAGAAGTCAGACAAGTAGCGAAGCTACACGATAGTGACACTTCCAAGAAATACGTGGGTTACTGTCCAGAAAGTCGGCATGGATCACGAAGTGACT"

def nucleotideA(theString):
        letterA = 0
        for letter in theString:
            if letter == "A":
                letterA += 1
        return letterA            

def nucleotideC(theString):
        letterC = 0
        for letter in theString:
            if letter == "C":
                letterC += 1
        return letterC            

def nucleotideG(theString):
        letterG = 0
        for letter in theString:
            if letter == "G":
                letterG += 1
        return letterG            

def nucleotideT(theString):
        letterT = 0
        for letter in theString:
            if letter == "T":
                letterT += 1
        return letterT            

letterA = nucleotideA(theString)
letterC = nucleotideC(theString)
letterG = nucleotideG(theString)
letterT = nucleotideT(theString)

print(f'{letterA} {letterC} {letterG} {letterT}')